---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure PHP packages are installed.
  apt:
    name: libapache2-mod-php5
    state: present
  when: php_enable_webserver
  notify: restart webserver

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
  with_items: "{{ php_packages }}"
  register: php_package_install
  notify: restart webserver

- name: Ensure php log dir exists
  file:
    path: /var/log/php
    owner: "{{ __php_fpm_pool_user }}"
    group: "{{ __php_fpm_pool_group }}"
    state: directory
    mode: 0755

- name: Ensure php tmp dir exists
  file:
    path: /tmp/www
    owner: "{{ __php_fpm_pool_user }}"
    group: "{{ __php_fpm_pool_group }}"
    state: directory
    mode: 0755

- name: Delete APCu configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_apc_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_enable_apc and php_package_install.changed
  notify: restart webserver

- name: Delete OpCache configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_opcache_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_opcache_enable and php_package_install.changed
  notify: restart webserver
